### ISSUE TITLE
Formatting only works if it's forced.

### ISSUE THREAD

**Issue by OmkoBass** [TheSwordBreaker/vite-reactts-eslint-prettier#7]
Formatting does not work regularly, the only way it will work is if I use ctrl + shift + P and then click Format Document (Forced)

**Comment by TheSwordBreaker** [comment]
There is vs code option to format on save which you need to activate

**Comment by OmkoBass** [comment]
Yeah i have format on save active, but it's not working. For some reason only when i use forced formatting it works. I set prettier as my default formater too.

**Comment by TheSwordBreaker** [comment]
Will I think I have not mentioned the step I used in vs codes in Read.me

first, let's solve the problem then I will update the readme

step I used in vs code 

1. Install Eslint and prettier extension for vs code.
2. Make Sure Both are enabled 
3. Make sure all packages are Installed. (Mostly Eslint and prettier in node_modules)
4. Enable formatOnSave of vs code
5. Open a .tsx file and check if the bottom right corners of vs code have Eslint and Prettier with a double tick 


![Screenshot (253)_LI](https://user-images.githubusercontent.com/52120562/162486286-7383a737-d555-4f9b-a4dd-c4a81deb7b96.jpg)



If Everything is Good Then It Should Work

But If Problem persist then try to save a file and share your screenshot of the output for a prettier extension like this

![Screenshot (251)](https://user-images.githubusercontent.com/52120562/162485791-5f29174e-f9d5-41a3-99cb-d869cde68c24.png)

**Comment by OmkoBass** [comment]
I already tried this, but this time i cloned a fresh repo, did all of the things you mentioned and everything works fine. Thank you!

**Comment by amelinium23** [comment]
> Will I think I have not mentioned the step I used in vs codes in Read.me
> 
> first, let's solve the problem then I will update the readme
> 
> step I used in vs code
> 
> 1. Install Eslint and prettier extension for vs code.
> 2. Make Sure Both are enabled
> 3. Make sure all packages are Installed. (Mostly Eslint and prettier in node_modules)
> 4. Enable formatOnSave of vs code
> 5. Open a .tsx file and check if the bottom right corners of vs code have Eslint and Prettier with a double tick
> 
> ![Screenshot (253)_LI](https://user-images.githubusercontent.com/52120562/162486286-7383a737-d555-4f9b-a4dd-c4a81deb7b96.jpg)
> 
> If Everything is Good Then It Should Work
> 
> But If Problem persist then try to save a file and share your screenshot of the output for a prettier extension like this
> 
> ![Screenshot (251)](https://user-images.githubusercontent.com/52120562/162485791-5f29174e-f9d5-41a3-99cb-d869cde68c24.png)

There is a setting in `settings.json` called `editor.codeActionsOnSave` that force to fix all problems in your code, so it's useful.
```json
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  }
```
